#########################
## Sample Sass Lint File
#########################
# Linter Options
# options:
#   # Don't merge default rules
#   merge-default-rules: false
#   # Set the formatter to 'html'
#   formatter: html
#   # Output file instead of logging results
#   output-file: 'linters/sass-lint.html'
# File Options
files:
  include: 'sass/**/*.s+(a|c)ss'
  ignore:
    - 'nodes_modules/**/*.*'
# Rule Configuration
rules:
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2
  mixins-before-declarations:
    - 2
    -
      exclude:
        - breakpoint
        - mq

  no-warn: 1
  no-debug: 1
  no-ids: 1
  no-important: 1
  hex-notation:
    - 1
    -
      style: uppercase
  indentation:
    - 1
    -
      size: 4
  leading-zero: 1
  property-sort-order: 0
